# Generated by Django 3.2.13 on 2022-08-31 12:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.IntegerField()),
                ('nip', models.CharField(blank=True, default=None, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('regon', models.CharField(blank=True, default=None, max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator('^\\d{1,9}$')])),
                ('street', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
